<div id="pageContainer" class="container" style="padding-left: 0px; padding-right: 0px; background-color: #0b1112; "><?php //if(isset($_GET['f'])){ echo $_GET['f']; } exit;        ?>
	<div class="subContainer" style="padding: 0px;">
		<?php $this->renderPartial('_sideBar', array()); ?>
		<!--        <a href="/"><img src="/webassets/images/banners/main_eng.jpg" style="position: relative; max-width: 102.6%; left: -7px;"/> </a>-->
		

		<div class="marketing-container" style="width: 90%;margin: 0 auto;">
			<div class="row">
				<div class="col-md-6">
					<div class="boxes">
						<h3 style="text-align: left; color: #edbc5a;font-weight: 300;">New Sweepstakes</h3>
						<p style="text-align: left; color: #ffffff; font-size: 13px;margin-bottom:20px;">
						Play the exciting Trivia Quiz sweepstakes. Answer questions to win entries into a 
						sweepstakes drawing for a $10,000. Players test their general knowledge
						with unique questions in a fun multiple choice answer format. The more questions you 
						answer correctly the more you entries you win. No purchase is necessary to play, but 
						for convenience and entertainment, additional gameplay is available from as little as $5.
						</p>
						
						<a href="/pickgame" class="no-decoration">
<!--							<img class="play-now-btn" src="/webassets/images/buttons/play-now-01.png"/>-->
					<div class="default-button">PLAY NOW</div>
						</a>
					</div>
				</div>
				<div class="col-md-6">
					<div class="boxes">
						<h3 style="text-align: left; color: #edbc5a;font-weight: 300;">How to play.</h3>
						<p style="text-align: left; color: #ffffff; font-size: 13px;">
						The sweepstakes’ drawings will be held after the close of 
						each entry period and all entries to each drawing must be 
						received before the close of the associated game. Users can
						play the games on our mobile friendly website by registering
						an account, paying the associated fee and picking the correct
						answers to their questions. There is also a way to play for free,
						check the website terms for more information.
						There is also a free method to participate, check the website
						for more information and requirements. After registering your
						account and adding credits through a valid credit card, answer
						the trivia questions. Users will receive one additional entry with
						each correct answer to the trivia questions. Winners will be announced at
						the end of the game in the winners section of the website.
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<div class="boxes">
						<h3 style="text-align: left; color: #edbc5a;font-weight: 300;">Prizes.</h3>
						<p style="text-align: left; color: #ffffff; font-size: 13px;">
						Grand Prize: $10,000
					</div>
				</div>
				<div class="col-md-4">
					<div class="boxes">
						<h3 style="text-align: left; color: #edbc5a;font-weight: 300;">The Winners</h3>
						<p style="text-align: left; color: #ffffff; font-size: 13px;">
						The winning sweepstakes entry for each drawing will be selected
						randomly from all sweepstakes entries generated by participating gameplay,
						prior to the close of the relevant game. The prize draw will take place after
						the advertised close of each game per the rules and terms of service
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<div class="boxes">
						<h3 style="text-align: left; color: #edbc5a;font-weight: 300;">The Questions</h3>
						<p style="text-align: left; color: #ffffff; font-size: 13px;">
						Questions are trivia based and each correct answer will get you
						an additional entry, so answer them now for your chance to win.
						</p>
					</div>
				</div>
			</div>  <!--end of row-->
		</div> <!--end of marketing-container-->
	</div> <!--end of sub container-->
</div> <!--end of page container-->